project:
  type: website

website:
  title: "Clinical Programming Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: Projects
        href: projects/
      - text: Blog
        href: blog/
      - href: certifications.qmd
        text: Certifications
      - href: agile.qmd
        text: Agile Methodologies
      - text: "Resources"
        href: resources/

format:
  html:
    theme: cosmo
    css: styles.css
