
project:
  type: website
  output-dir: "."

website:
  title: "Clinical Programming Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: Projects
        menu:
          - text: "Survival Analysis"
            href: projects/survival_analysis/survival_analysis_parallel.qmd
          - text: "SAS Oncology Report"
            href: projects/sas-oncology-report.qmd
          - text: "R Survival Analysis"
            href: projects/r-survival-analysis.qmd
          - text: "Demographic Table"
            href: projects/demographic-table.qmd
      - href: blog/
        text: Blog
      - href: agile.qmd
        text: Agile Methodologies
      - href: certifications.qmd
        text: Certifications
      - text: "Resources"
        href: resources/
      - text: Survival Analysis Theory
        href: survival-theory.qmd

format:
  html:
    theme: cosmo
    css: styles.css
